version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres && psql --username=postgres --list" ]
      timeout: 10s
      retries: 20
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: transfer-api/go-server
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      DB_URL: "user=postgres dbname=postgres password=postgres sslmode=disable host=postgresql port=5432"
      PORT: "8000"
    links:
      - postgresql

